# Generated by Django 3.0.6 on 2020-10-27 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Chanson_du_mois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ijambo.Music')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=20)),
                ('cover', models.ImageField(upload_to='music/covers')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ijambo.Music')),
            ],
        ),
    ]
